---
- name: Restrict supported key exchange, cipher, and MAC algorithms
  ansible.builtin.include_tasks:
    file: 'ssh-server/modules/kcm.yml'
  when: hsesa_restrict_kcm | bool

- name: Generate ED25519 and RSA keys
  ansible.builtin.include_tasks:
    file: 'ssh-server/modules/key.yml'
  when: hsesa_regenerate_ssh_host_keys | bool
